targets:
  $default:
    builders:
      kiwi:
      built_value_generator|built_value:
        generate_for:
          exclude:
              - test/**
              - lib/data/data_sources/**/*data_source.dart